import { rm, mkdir, cp, readFile, writeFile, access } from "node:fs/promises";
import path from "node:path";

// Absolute path to the project root.
// process.cwd() returns the folder from which the script is executed.
const ROOT = process.cwd();

// Absolute path to the source folder.
// All editable project files live inside src/.
const SRC = path.join(ROOT, "src");

// Absolute path to the output folder.
// This folder is generated by the build and can be deleted/recreated at any time.
const DIST = path.join(ROOT, "dist");

// Check whether a file or folder exists.
// This avoids crashing when trying to copy a missing folder.
async function exists(targetPath) {
    try {
        await access(targetPath);
        return true;
    } catch {
        return false;
    }
}

// Delete the old output folder and recreate it from scratch.
// This ensures the build always starts from a clean state.
async function cleanDist() {
    await rm(DIST, { recursive: true, force: true });
    await mkdir(DIST, { recursive: true });
}

// Copy a directory only if it exists.
// Useful for assets/ and static/ folders.
async function copyDirIfExists(from, to) {
    if (!(await exists(from))) {
        console.warn(`Skipped missing directory: ${from}`);
        return;
    }

    // Make sure the parent directory exists before copying.
    await mkdir(path.dirname(to), { recursive: true });

    // Copy the full directory recursively.
    await cp(from, to, { recursive: true });
}

// Load and parse a JSON file located inside src/.
// Example: loadJson("data/base/profile.json")
async function loadJson(relativePath) {
    const filePath = path.join(SRC, relativePath);
    const content = await readFile(filePath, "utf-8");
    return JSON.parse(content);
}

// Escape text before injecting it into HTML.
// This prevents broken markup and is a good habit for generated pages.
function escapeHtml(value = "") {
    return String(value)
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#39;");
} 

function renderListItems(items = []) {
  return items
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("");
}

function renderInlineStrongList(items = []) {
  return items
    .map((item) => `<strong>${escapeHtml(item)}</strong>`)
    .join(", ");
}

// Build the very first page of the project.
// For now, this function only generates one page:
// /fr/cv/designer/index.html
async function buildFirstPage() {
  // Load base data
  const profile = await loadJson("data/base/profile.json");
  const contact = await loadJson("data/base/contact.json");
  const education = await loadJson("data/base/education.json");
  const skills = await loadJson("data/base/skills.json");
  const projects = await loadJson("data/base/projects.json");
  const languages = await loadJson("data/base/languages.json");

  // Load French locale files
  const localeCommon = await loadJson("locales/fr/common.json");
  const localeDesigner = await loadJson("locales/fr/cv-designer.json");

  // Output directory for this page
  const outDir = path.join(DIST, "fr", "cv", "designer");
  await mkdir(outDir, { recursive: true });

  // Read translated content with fallbacks.
  // Optional chaining (?.) prevents crashes if a key is missing.
  // Nullish coalescing (??) provides a fallback value.
  const pageTitle = localeDesigner?.cv?.designer?.title ?? "Designer Numérique junior";
  const pageSummary = localeDesigner?.cv?.designer?.summary ?? "Résumé indisponible";
  const summaryLabel = localeCommon?.sections?.summary ?? "Résumé professionnel";
  const contactLabel = localeCommon?.sections?.contact ?? "Contact";
  const educationLabel = localeCommon?.sections?.education ?? "Formation";
  const skillsLabel = localeCommon?.sections?.skills ?? "Compétences";
  const projectsLabel = localeCommon?.sections?.projects ?? "Projets et expérience pratique";
  const languagesLabel = localeCommon?.sections?.languages ?? "Langues";

  // Contact / links
  const githubUrl = contact?.links?.github ?? "";
  const linkedinUrl = contact?.links?.linkedin ?? "";

  // Education HTML
  const educationHtml = (education?.items ?? [])
    .map((item) => {
      const certification = item.certification
        ? ` (${escapeHtml(item.certification)})`
        : "";

      const schoolLine = [
        escapeHtml(item.school ?? ""),
        item.period ? `(${escapeHtml(item.period)})` : "",
        item.location ? escapeHtml(item.location) : "",
      ]
        .filter(Boolean)
        .join(", ");

      return `
        <p>
          <strong>${escapeHtml(item.title ?? "")}</strong>${certification}
          ${schoolLine ? `- ${schoolLine}` : ""}
        </p>
      `;
    })
    .join("");

  // Skills HTML
  const skillsHtml = (skills?.skills?.groups ?? [])
    .map((group) => {
      return `
        <li>
          ${escapeHtml(group.label ?? "")}: ${renderInlineStrongList(group.items ?? [])}
        </li>
      `;
    })
    .join("");

  // Projects HTML
  const projectsHtml = (projects?.items ?? [])
    .map((project) => {
      const stackText = (project.stack ?? []).join("/");

      const highlightsHtml = renderListItems(project.highlights ?? []);

      const liveLink = project?.links?.live
        ? `<a href="${escapeHtml(project.links.live)}" target="_blank" rel="noopener noreferrer">Voir le projet</a>`
        : "";

      const githubLink = project?.links?.github
        ? `<a href="${escapeHtml(project.links.github)}" target="_blank" rel="noopener noreferrer">GitHub</a>`
        : "";

      const linksHtml = [liveLink, githubLink].filter(Boolean).join(" · ");

      return `
        <article>
          <h3>
            ${escapeHtml(project.title ?? "")}
            ${stackText ? `(${escapeHtml(stackText)})` : ""}
          </h3>
          ${
            project.summary
              ? `<p>${escapeHtml(project.summary)}</p>`
              : ""
          }
          ${
            highlightsHtml
              ? `<ul>${highlightsHtml}</ul>`
              : ""
          }
          ${
            linksHtml
              ? `<p>${linksHtml}</p>`
              : ""
          }
        </article>
      `;
    })
    .join("");

  // Languages HTML
  const languagesHtml = (languages?.items ?? [])
    .map((language) => {
      return `
        <li>
          ${escapeHtml(language.name ?? "")}: ${escapeHtml(language.level ?? "")}
        </li>
      `;
    })
    .join("");

    // Generate the HTML page as a template string.
    // This is fine for a first step. Later, we can move to real templates.
  const html =
  `<!DOCTYPE html>
  <html lang="fr">
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>${escapeHtml(pageTitle)} - ${escapeHtml(profile.name ?? "")}</title>
    <meta name="description" content="${escapeHtml(pageSummary)}"/>
    <link rel="stylesheet" href="/assets/css/style.css"/>
    <link rel="icon" href="/assets/img/favicon.png"/>
  </head>
  <body>
    <header>
      <h1>${escapeHtml(profile.name ?? "")}</h1>
      <address>
        ${
          contact?.location
            ? `<p>${escapeHtml(contact.location)}</p>`
            : ""
        }
        ${
          contact?.email
            ? `<p><a href="mailto:${escapeHtml(contact.email)}">${escapeHtml(contact.email)}</a></p>`
            : ""
        }
      </address>

      ${
        githubUrl || linkedinUrl
      ? `
      <div class="social-links" aria-label="Réseaux sociaux">
        <nav aria-label="Liens professionnels">
          <ul>
            ${githubUrl ?
              `<li>
                <a href="${escapeHtml(githubUrl)}" target="_blank" rel="noopener noreferrer">
                  <svg viewBox="0 0 24 24" class="social-icon">
                    <g>
                      <path d="M12,0.296c-6.627,0-12,5.372-12,12c0,5.302,3.438,9.8,8.206,11.387   c0.6,0.111,0.82-0.26,0.82-0.577c0-0.286-0.011-1.231-0.016-2.234c-3.338,0.726-4.043-1.416-4.043-1.416   C4.421,18.069,3.635,17.7,3.635,17.7c-1.089-0.745,0.082-0.729,0.082-0.729c1.205,0.085,1.839,1.237,1.839,1.237   c1.07,1.834,2.807,1.304,3.492,0.997C9.156,18.429,9.467,17.9,9.81,17.6c-2.665-0.303-5.467-1.332-5.467-5.93   c0-1.31,0.469-2.381,1.237-3.221C5.455,8.146,5.044,6.926,5.696,5.273c0,0,1.008-0.322,3.301,1.23   C9.954,6.237,10.98,6.104,12,6.099c1.02,0.005,2.047,0.138,3.006,0.404c2.29-1.553,3.297-1.23,3.297-1.23   c0.653,1.653,0.242,2.873,0.118,3.176c0.769,0.84,1.235,1.911,1.235,3.221c0,4.609-2.807,5.624-5.479,5.921   c0.43,0.372,0.814,1.103,0.814,2.222c0,1.606-0.014,2.898-0.014,3.293c0,0.319,0.216,0.694,0.824,0.576   c4.766-1.589,8.2-6.085,8.2-11.385C24,5.669,18.627,0.296,12,0.296z"/>
	                    <path d="M4.545,17.526c-0.026,0.06-0.12,0.078-0.206,0.037c-0.087-0.039-0.136-0.121-0.108-0.18   c0.026-0.061,0.12-0.078,0.207-0.037C4.525,17.384,4.575,17.466,4.545,17.526L4.545,17.526z"/>
	                    <path d="M5.031,18.068c-0.057,0.053-0.169,0.028-0.245-0.055c-0.079-0.084-0.093-0.196-0.035-0.249   c0.059-0.053,0.167-0.028,0.246,0.056C5.076,17.903,5.091,18.014,5.031,18.068L5.031,18.068z"/>
	                    <path d="M5.504,18.759c-0.074,0.051-0.194,0.003-0.268-0.103c-0.074-0.107-0.074-0.235,0.002-0.286   c0.074-0.051,0.193-0.005,0.268,0.101C5.579,18.579,5.579,18.707,5.504,18.759L5.504,18.759z"/>
                      <path d="M6.152,19.427c-0.066,0.073-0.206,0.053-0.308-0.046c-0.105-0.097-0.134-0.234-0.068-0.307   c0.067-0.073,0.208-0.052,0.311,0.046C6.191,19.217,6.222,19.355,6.152,19.427L6.152,19.427z"/>
	                    <path d="M7.047,19.814c-0.029,0.094-0.164,0.137-0.3,0.097C6.611,19.87,6.522,19.76,6.55,19.665   c0.028-0.095,0.164-0.139,0.301-0.096C6.986,19.609,7.075,19.719,7.047,19.814L7.047,19.814z"/>
  	                  <path d="M8.029,19.886c0.003,0.099-0.112,0.181-0.255,0.183c-0.143,0.003-0.26-0.077-0.261-0.174c0-0.1,0.113-0.181,0.256-0.184   C7.912,19.708,8.029,19.788,8.029,19.886L8.029,19.886z"/>
                      <path d="M8.943,19.731c0.017,0.096-0.082,0.196-0.224,0.222c-0.139,0.026-0.268-0.034-0.286-0.13   c-0.017-0.099,0.084-0.198,0.223-0.224C8.797,19.574,8.925,19.632,8.943,19.731L8.943,19.731z"/>
                    </g>
                  </svg>
                </a>
              </li>` : ""}
            ${linkedinUrl ?
              `<li>
                <a href="${escapeHtml(linkedinUrl)}" target="_blank" rel="noopener noreferrer">
                  <svg viewBox="0 0 24 24" class="social-icon">
                    <g>
	                    <path d="M17.291,19.073h-3.007v-4.709c0-1.123-0.02-2.568-1.564-2.568c-1.566,0-1.806,1.223-1.806,2.487v4.79H7.908   V9.389h2.887v1.323h0.04c0.589-1.006,1.683-1.607,2.848-1.564c3.048,0,3.609,2.005,3.609,4.612L17.291,19.073z M4.515,8.065   c-0.964,0-1.745-0.781-1.745-1.745c0-0.964,0.781-1.745,1.745-1.745c0.964,0,1.745,0.781,1.745,1.745   C6.26,7.284,5.479,8.065,4.515,8.065L4.515,8.065 M6.018,19.073h-3.01V9.389h3.01V19.073z M18.79,1.783H1.497   C0.68,1.774,0.01,2.429,0,3.246V20.61c0.01,0.818,0.68,1.473,1.497,1.464H18.79c0.819,0.01,1.492-0.645,1.503-1.464V3.245   c-0.012-0.819-0.685-1.474-1.503-1.463"/>
                    </g>
                  </svg>
                </a>
              </li>` : ""}
          </ul>
        </nav>
      </div>
      `
          : ""
      }
    </header>

  <main>
    <section>
      <h2>${escapeHtml(summaryLabel)}</h2>
      <p>${escapeHtml(pageSummary)}</p>
    </section>

    <section>
      <h2>${escapeHtml(educationLabel)}</h2>
      ${educationHtml}
    </section>

    <section>
      <h2>${escapeHtml(skillsLabel)}</h2>
      <ul>
        ${skillsHtml}
      </ul>
    </section>

    <section>
      <h2>${escapeHtml(projectsLabel)}</h2>
      ${projectsHtml}
    </section>

    <section>
      <h2>${escapeHtml(languagesLabel)}</h2>
      <ul>
        ${languagesHtml}
      </ul>
    </section>
  </main>

  <script src="/assets/js/script.js" defer></script>
  </body>
</html>`;

  // Write the generated HTML file to the output folder
  await writeFile(path.join(outDir, "index.html"), html, "utf-8");
}

// Main build function.
// This is the global entry point of the project build.
async function main() {
    // 1) Start from a clean output folder.
    await cleanDist();

    // 2) Copy shared assets (CSS, JS, images, icons...).
    await copyDirIfExists(path.join(SRC, "assets"), path.join(DIST, "assets"));

    // 3) Copy static files as-is (_headers, _redirects, robots.txt, PDFs...).
    await copyDirIfExists(path.join(SRC, "static"), DIST);

    // 4) Generate the first HTML page.
    await buildFirstPage();

    console.log("Build completed successfully.");
}

// Run the build.
// If any step fails, print the error and exit with a failure code.
main().catch((error) => {
  console.error("Build failed:", error);
  process.exit(1);
});