import { rm, mkdir, cp, readFile, writeFile, access } from "node:fs/promises";
import path from "node:path";

// Absolute path to the project root.
// process.cwd() returns the folder from which the script is executed.
const ROOT = process.cwd();

// Absolute path to the source folder.
// All editable project files live inside src/.
const SRC = path.join(ROOT, "src");

// Absolute path to the output folder.
// This folder is generated by the build and can be deleted/recreated at any time.
const DIST = path.join(ROOT, "dist");

// Check whether a file or folder exists.
// This avoids crashing when trying to copy a missing folder.
async function exists(targetPath) {
    try {
        await access(targetPath);
        return true;
    } catch {
        return false;
    }
}

// Delete the old output folder and recreate it from scratch.
// This ensures the build always starts from a clean state.
async function cleanDist() {
    await rm(DIST, { recursive: true, force: true });
    await mkdir(DIST, { recursive: true });
}

// Copy a directory only if it exists.
// Useful for assets/ and static/ folders.
async function copyDirIfExists(from, to) {
    if (!(await exists(from))) {
        console.warn(`Skipped missing directory: ${from}`);
        return;
    }

    // Make sure the parent directory exists before copying.
    await mkdir(path.dirname(to), { recursive: true });

    // Copy the full directory recursively.
    await cp(from, to, { recursive: true });
}

// Load and parse a JSON file located inside src/.
// Example: loadJson("data/base/profile.json")
async function loadJson(relativePath) {
    const filePath = path.join(SRC, relativePath);
    const content = await readFile(filePath, "utf-8");
// Display the extact path if there's an error when returning a JSON.    
  try {
    return JSON.parse(content);
  } catch (error) {
    console.error(`Invalid JSON in: ${filePath}`);
    throw error;
  }
}


// Escape text before injecting it into HTML.
// This prevents broken markup and is a good habit for generated pages.
function escapeHtml(value = "") {
    return String(value)
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#39;");
} 

function renderListItems(items = []) {
  return items
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("");
}

function renderInlineStrongList(items = []) {
  return items
    .map((item) => `<strong>${escapeHtml(item)}</strong>`)
    .join(", ");
}

// Build the very first page of the project.
// For now, this function only generates one page:
// /fr/cv/designer/index.html
async function buildFirstPage() {
  // Load base data
  const profile = await loadJson("data/base/profile.json");
  const contact = await loadJson("data/base/contact.json");
  const education = await loadJson("data/base/education.json");
  const skills = await loadJson("data/base/skills.json");
  const projects = await loadJson("data/base/projects.json");
  const languages = await loadJson("data/base/languages.json");

  // Load French locale files
  const localeCommon = await loadJson("locales/fr/common.json");
  const localeDesigner = await loadJson("locales/fr/cv-designer.json");

  // Output directory for this page
  const outDir = path.join(DIST, "fr", "cv", "designer");
  await mkdir(outDir, { recursive: true });

  // Read translated content with fallbacks.
  // Optional chaining (?.) prevents crashes if a key is missing.
  // Nullish coalescing (??) provides a fallback value.
  const pageTitle = localeDesigner?.cv?.designer?.title ?? "Designer Numérique junior";
  const pageSummary = localeDesigner?.cv?.designer?.summary ?? "Résumé indisponible";
  const summaryLabel = localeCommon?.sections?.summary ?? "Résumé professionnel";
  const contactLabel = localeCommon?.sections?.contact ?? "Contact";
  const educationLabel = localeCommon?.sections?.education ?? "Formation";
  const skillsLabel = localeCommon?.sections?.skills ?? "Compétences";
  const projectsLabel = localeCommon?.sections?.projects ?? "Projets et expérience pratique";
  const languagesLabel = localeCommon?.sections?.languages ?? "Langues";

  // Contact / links
  const githubUrl = contact?.links?.github ?? "";
  const linkedinUrl = contact?.links?.linkedin ?? "";

  // Education HTML
  const educationHtml = (education?.items ?? [])
    .map((item) => {
      const certification = item.certification
        ? ` (${escapeHtml(item.certification)})`
        : "";

      const schoolLine = [
        escapeHtml(item.school ?? ""),
        item.period ? `(${escapeHtml(item.period)})` : "",
        item.location ? escapeHtml(item.location) : "",
      ]
        .filter(Boolean)
        .join(", ");

      return `
        <p>
          <strong>${escapeHtml(item.title ?? "")}</strong>${certification}
          ${schoolLine ? `- ${schoolLine}` : ""}
        </p>
      `;
    })
    .join("");

  // Skills HTML
  const skillsHtml = (skills?.skills?.groups ?? [])
    .map((group) => {
      return `
        <li>
          ${escapeHtml(group.label ?? "")}: ${renderInlineStrongList(group.items ?? [])}
        </li>
      `;
    })
    .join("");

  // Projects HTML
  const projectsHtml = (projects?.items ?? [])
    .map((project) => {
      const stackText = (project.stack ?? []).join("/");

      const highlightsHtml = renderListItems(project.highlights ?? []);

      const liveLink = project?.links?.live
        ? `<a href="${escapeHtml(project.links.live)}" target="_blank" rel="noopener noreferrer">Voir le projet</a>`
        : "";

      const githubLink = project?.links?.github
        ? `<a href="${escapeHtml(project.links.github)}" target="_blank" rel="noopener noreferrer">GitHub</a>`
        : "";

      const linksHtml = [liveLink, githubLink].filter(Boolean).join("");

      return `
        <article>
          <h3>
            ${escapeHtml(project.title ?? "")}
            ${stackText ? `(${escapeHtml(stackText)})` : ""}
          </h3>
          ${
            project.summary
              ? `<p>${escapeHtml(project.summary)}</p>`
              : ""
          }
          ${
            highlightsHtml
              ? `<ul>${highlightsHtml}</ul>`
              : ""
          }
          ${
            linksHtml
              ? `<p>${linksHtml}</p>`
              : ""
          }
        </article>
      `;
    })
    .join("");

  // Languages HTML
  const languagesHtml = (languages?.items ?? [])
    .map((language) => {
      return `
        <li>
          ${escapeHtml(language.name ?? "")}: ${escapeHtml(language.level ?? "")}
        </li>
      `;
    })
    .join("");

    // Generate the HTML page as a template string.
    // This is fine for a first step. Later, we can move to real templates.
  const html =
  `<!DOCTYPE html>
  <html lang="fr">
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>${escapeHtml(pageTitle)} - ${escapeHtml(profile.name ?? "")}</title>
    <meta name="description" content="${escapeHtml(pageSummary)}"/>
    <link rel="stylesheet" href="/assets/css/style.css"/>
    <link rel="stylesheet" href="/assets/css/win98-theme.css"/>
    <link rel="icon" href="/assets/img/favicon.png"/>
  </head>
  <body>
    <header>
      <h1>${escapeHtml(profile.name ?? "")}</h1>
      <address>
        ${
          contact?.location
            ? `<p>${escapeHtml(contact.location)}</p>`
            : ""
        }
        ${
          contact?.portfolio
            ? `<p><a href="mailto:${escapeHtml(contact.portfolio)}">${escapeHtml(contact.portfolio)}</a></p>`
            : ""
        }
      </address>

      ${
        githubUrl || linkedinUrl
      ? `
      <div class="social-links" aria-label="Réseaux sociaux">
        <nav aria-label="Liens professionnels">
          <ul>
            ${githubUrl ?
              `<li>
                <a href="${escapeHtml(githubUrl)}" target="_blank" rel="noopener noreferrer" class="btn">
                  <img src="/assets/img/github.webp" alt="">
                </a>
              </li>` : ""}
            ${linkedinUrl ?
              `<li>
                <a href="${escapeHtml(linkedinUrl)}" target="_blank" rel="noopener noreferrer" class="btn">
                  <img src="/assets/img/linkedin.webp" alt="">
                </a>
              </li>` : ""}
          </ul>
        </nav>
      </div>
      `
          : ""
      }
    </header>

  <main>
    <section class="window">
      <div class="titlebar">
        <div class="title">
          <img src="/assets/img/icons/desktop/resume.webp" alt="" aria-hidden="true">
          <span>CV</span>
        </div>
        <div class="controls">
          <button type="button" aria-label="Minimize window" aria-controls="win-home" disabled>
            <img src="/assets/img/icons/window/minimize.webp" alt="">
          </button>
          <button type="button" aria-label="Maximize window" aria-controls="win-home" disabled>
            <img src="/assets/img/icons/window/maximize.webp" alt="">
          </button>
          <button type="button" aria-label="Close window" aria-controls="win-home">
            <img src="/assets/img/icons/window/close.webp" alt="">
          </button>
        </div>
      </div>
      <h2 class="window-title">${escapeHtml(summaryLabel)}</h2>
      <div class="window window-home">
        <div class="window-content">
          <div class="home-content">
            <p>${escapeHtml(pageSummary)}</p>
            <h2>${escapeHtml(educationLabel)}</h2>
            ${educationHtml}
            <h2>${escapeHtml(skillsLabel)}</h2>
            <ul>
                ${skillsHtml}
            </ul>
            <h2>${escapeHtml(projectsLabel)}</h2>
            ${projectsHtml}
            <h2>${escapeHtml(languagesLabel)}</h2>
            <ul>
              ${languagesHtml}
            </ul>
          </div>
        </div>
      </div>
    </section>
  </main>

  <!-- Temporary print-oriented grouping for urgent application.
Refactor into semantic sections for the final online CV version. -->

  <script src="/assets/js/script.js" defer></script>
  </body>
</html>`;

  // Write the generated HTML file to the output folder
  await writeFile(path.join(outDir, "index.html"), html, "utf-8");
}

// Main build function.
// This is the global entry point of the project build.
async function main() {
    // 1) Start from a clean output folder.
    await cleanDist();

    // 2) Copy shared assets (CSS, JS, images, icons...).
    await copyDirIfExists(path.join(SRC, "assets"), path.join(DIST, "assets"));

    // 3) Copy static files as-is (_headers, _redirects, robots.txt, PDFs...).
    await copyDirIfExists(path.join(SRC, "static"), DIST);

    // 4) Generate the first HTML page.
    await buildFirstPage();

    console.log("Build completed successfully.");
}

// Run the build.
// If any step fails, print the error and exit with a failure code.
main().catch((error) => {
  console.error("Build failed:", error);
  process.exit(1);
});