import { rm, mkdir, cp, readFile, writeFile, access } from "node:fs/promises";
import path from "node:path";

// Absolute path to the project root.
// process.cwd() returns the folder from which the script is executed.
const ROOT = process.cwd();

// Absolute path to the source folder.
// All editable project files live inside src/.
const SRC = path.join(ROOT, "src");

// Absolute path to the output folder.
// This folder is generated by the build and can be deleted/recreated at any time.
const DIST = path.join(ROOT, "dist");

// Check whether a file or folder exists.
// This avoids crashing when trying to copy a missing folder.
async function exists(targetPath) {
    try {
        await access(targetPath);
        return true;
    } catch {
        return false;
    }
}

// Delete the old output folder and recreate it from scratch.
// This ensures the build always starts from a clean state.
async function cleanDist() {
    await rm(DIST, { recursive: true, force: true });
    await mkdir(DIST, { recursive: true });
}

// Copy a directory only if it exists.
// Useful for assets/ and static/ folders.
async function copyDirIfExists(from, to) {
    if (!(await exists(from))) {
        console.warn(`Skipped missing directory: ${from}`);
        return;
    }

    // Make sure the parent directory exists before copying.
    await mkdir(path.dirname(to), { recursive: true });

    // Copy the full directory recursively.
    await cp(from, to, { recursive: true });
}

// Load and parse a JSON file located inside src/.
// Example: loadJson("data/base/profile.json")
async function loadJson(relativePath) {
    const filePath = path.join(SRC, relativePath);
    const content = await readFile(filePath, "utf-8");
    return JSON.parse(content);
}

// Escape text before injecting it into HTML.
// This prevents broken markup and is a good habit for generated pages.
function escapeHtml(value = "") {
    return String(value)
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#39;");
}

// Build the very first page of the project.
// For now, this function only generates one page:
// /fr/cv/designer/index.html
async function buildFirstPage() {
    // Load base data
    const profile = await loadJson("data/base/profile.json");
    const contact = await loadJson("data/base/contact.json");

    // Load French locale files.
    const localeCommon = await loadJson("locales/fr/common.json");
    const localeDesigner = await loadJson("locales/fr/cv-designer.json");

    // Output directory for this page.
    const outDir = path.join(DIST, "fr", "cv", "designer");
    await mkdir(outDir, { recursive: true });

    // Read translated content with fallbacks.
    // Optional chaining (?.) prevents crashes if a key is missing.
    // Nullish coalescing (??) provides a fallback value.
    const pageTitle = localeDesigner?.cv?.designer?.title ?? "Designer Numérique junior";

    const pageSummary = localeDesigner?.cv?.designer?.summary ?? "Résumé indisponible";

    const summaryLabel = localeCommon?.sections?.summary ?? "Résumé";
    
    const contactLabel = localeCommon?.sections?.contact ?? "Contact";

     // Generate the HTML page as a template string.
  // This is fine for a first step. Later, we can move to real templates.
  const html =
  `<!DOCTYPE html>
  <html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(pageTitle)} - ${escapeHtml(profile.name ?? "")}</title>
    <link rel="stylesheet" href="/assets/css/style.css" />
  </head>
  <body>
    <header>
      <nav aria-label="CV variant switcher">
        <a href="/fr/cv/designer/">Designer</a>
        <a href="/fr/cv/fullstack/">Full Stack</a>
      </nav>
    </header>

    <main>
      <section>
        <h1>${escapeHtml(profile.name ?? "")}</h1>
        <p>${escapeHtml(pageTitle)}</p>
      </section>

      <section>
        <h2>${escapeHtml(summaryLabel)}</h2>
        <p>${escapeHtml(pageSummary)}</p>
      </section>

      <section>
        <h2>${escapeHtml(contactLabel)}</h2>
        <ul>
          <li>${escapeHtml(contact.email ?? "")}</li>
          <li>${escapeHtml(contact.location ?? "")}</li>
        </ul>
      </section>
    </main>

    <script src="/assets/js/script.js" defer></script>
  </body>
  </html>`;
    
    // Write the generated HTML file to the output folder.
    await writeFile(path.join(outDir, "index.html"), html, "utf-8");
}

// Main build function.
// This is the global entry point of the project build.
async function main() {
    // 1) Start from a clean output folder.
    await cleanDist();

    // 2) Copy shared assets (CSS, JS, images, icons...).
    await copyDirIfExists(path.join(SRC, "assets"), path.join(DIST, "assets"));

    // 3) Copy static files as-is (_headers, _redirects, robots.txt, PDFs...).
    await copyDirIfExists(path.join(SRC, "static"), DIST);

    // 4) Generate the first HTML page.
    await buildFirstPage();

    console.log("Build completed successfully.");
}

// Run the build.
// If any step fails, print the error and exit with a failure code.
main().catch((error) => {
  console.error("Build failed:", error);
  process.exit(1);
});